Ingredient.create(name: "lemon juice")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "gin")
Ingredient.create(name: "sugar syrup")
Ingredient.create(name: "egg white")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "rooty moot")
Ingredient.create(name: "tonic")
Ingredient.create(name: "lime")
Ingredient.create(name: "sweet vermouth")
Ingredient.create(name: "campari")
Ingredient.create(name: "negroni pre-mix")
Ingredient.create(name: "juniper berries")
Ingredient.create(name: "cranberries")
Ingredient.create(name: "ice")
Ingredient.create(name: "lemon slice")
Ingredient.create(name: "lime slice")
Ingredient.create(name: "lemon rind")
Ingredient.create(name: "lime rind")
Ingredient.create(name: "orange rind")
